/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-01 05:49:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.diary;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import myplant.model.vo.Myplant;
import java.sql.Date;
import member.model.vo.Member;
import common.Paging;

public final class myplant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/diary/../../views/common/sidebar.jsp", Long.valueOf(1693547379175L));
    _jspx_dependants.put("/views/diary/../diary/myplantPagingView.jsp", Long.valueOf(1693531624000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("common.Paging");
    _jspx_imports_classes.add("myplant.model.vo.Myplant");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");

	ArrayList<Myplant> list = (ArrayList<Myplant>)request.getAttribute("list");	

	int nowpage = 1;
	if(request.getAttribute("currentPage") != null){
		nowpage = ((Integer)request.getAttribute("currentPage")).intValue();
	}

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>malant</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/malant/resources/common/css/scrolling.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/malant/resources/common/css/font.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/malant/resources/diary/css/myplant.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/malant/resources/common/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("        ");
      out.write('\n');

	Member loginMember = (Member) session.getAttribute("loginMember");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"/malant/resources/common/css/sidebar.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"/malant/resources/common/css/font.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"sidebar\">\n");
      out.write("		<div class=\"sidebar-header\">\n");
      out.write("			<span class=\"sidebar-title\"><a href=\"/malant\"> <img\n");
      out.write("					src=\"/malant/resources/common/images/main_tilte.gif\" alt=\"식물 검색\" /></a></span>\n");
      out.write("		</div>\n");
      out.write("		<section>\n");
      out.write("			<ul id=\"new_categories\">\n");
      out.write("				<li><a href=\"/malant\">식물 검색</a></li>\n");
      out.write("				<li><a href=\"/malant/views/board/boardMainList.jsp\">커뮤니티</a></li>\n");
      out.write("				<li><a \n");
      out.write("				");
 if(loginMember == null) { 
      out.write("\n");
      out.write("					href=\"/malant/views/member/loginPage.jsp\"\n");
      out.write("				");
 }else { 
      out.write("\n");
      out.write("					href=\"/malant/mplist?user_no=");
      out.print( loginMember.getUserNo() );
      out.write("\"\n");
      out.write("				");
 } 
      out.write(">다이어리</a></li>\n");
      out.write("				<li><a href=\"\">전국 식물원</a></li>\n");
      out.write("				<li><a href=\"/malant/smplist\">스토어</a></li>\n");
      out.write("				<li><a href=\"/malant/views/notice/noticeMainList.jsp\">공지/이벤트</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</section>\n");
      out.write("		<!-- 로그인 영역 -->\n");
      out.write("		");
 if (loginMember == null) { // 로그인하지 않았을 때 
      out.write("\n");
      out.write("			<div class=\"login-section\">\n");
      out.write("				<hr solid color=\"#ddd\" />\n");
      out.write("				<div class=\"login-box\" onclick=\"location.href='/malant/views/member/loginPage.jsp;'\">\n");
      out.write("					로그인하러 가기\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<!-- 회원가입/아이디/비밀번호 찾기 영역 -->\n");
      out.write("			<div class=\"account-section\">\n");
      out.write("				<a href=\"/malant/views/member/enrollMember.jsp\" class=\"account-link\">회원가입</a><span class=\"login-divide\">|</span>\n");
      out.write("				<!-- 아이디/비밀번호 찾기는 새창을 띄워 진행 -->\n");
      out.write("				<a href=\"#\" class=\"account-link\" onclick=\"window.open('/malant/findAccount.jsp?find=id', '_blank', 'width=900, height=1000');\">아이디찾기</a><span class=\"login-divide\">|</span>\n");
      out.write("				<a href=\"#\"	class=\"account-link\" onclick=\"window.open('/malant/findAccount.jsp?find=pwd', '_blank', 'width=900, height=1000');\">비밀번호재설정</a>\n");
      out.write("			</div>\n");
      out.write("		");
 } else { 
      out.write("\n");
      out.write("			<div class=\"login-section\">\n");
      out.write("				");
      out.print( loginMember.getNickname() );
      out.write("님 환영합니다.<br>\n");
      out.write("				\n");
      out.write("				<a href=\"/malant/views/member/confirmMemberBeforeInfo.jsp?userid=");
      out.print( loginMember.getUserId() );
      out.write("\">마이페이지</a> &nbsp; \n");
      out.write("				<a href=\"/malant/logout\">로그아웃</a>\n");
      out.write("			</div>\n");
      out.write("		");
 } 
      out.write("\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("	<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"menu\"><a href=\"/malant/views/diary/diary.jsp\">다이어리</a></div> \r\n");
      out.write("		<div class=\"menu\"><a href=\"/malant/views/diary/calendar.jsp\">캘린더</a></div> \r\n");
      out.write("		<div class=\"menu\"><a href=\"/malant/views/diary/myplant.jsp\">반려식물</a></div>	\r\n");
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	<div id=\"contentbody\">   \r\n");
      out.write("	\r\n");
      out.write("	<div class=\"pagingview\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");

	Paging paging = (Paging)request.getAttribute("paging");
	
	int startPage = paging.getStartPage();
	int endPage = paging.getEndPage();
	int maxPage = paging.getMaxPage();
	int currentPage = paging.getCurrentPage();
	int limit = paging.getLimit();
	
	String urlMapping = paging.getUrlMapping();
	
	String action = (String)request.getAttribute("action");
	String keyword = null, begin = null, end = null;
 
	if(action != null){
		if(action.equals("date")) {
			begin = (String)request.getAttribute("begin");
			end = (String)request.getAttribute("end");
		}else {
			keyword = (String)request.getAttribute("keyword");
		}
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 if(action == null){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=1\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - limit) < startPage && (currentPage - limit) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - limit );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + limit) > endPage && (currentPage + limit) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + limit );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 if(action != null && keyword != null){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=1&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - limit) < startPage && (currentPage - limit) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - limit );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + limit) > endPage && (currentPage + limit) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + limit );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 if(action != null && action.equals("date")){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=1&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - limit) < startPage && (currentPage - limit) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - limit );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + limit) > endPage && (currentPage + limit) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + limit );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/malant/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
 if (list.size() > 0 ) { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"addYourPlant\" class=\"addYourPlant\"> 반려식물을 등록해주세요! </div>\r\n");
      out.write("			<form action=\"/malant/mpnew\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("			<div id=\"myplantAdd\" class=\"myplantAdd\"> 반려식물 등록화면 (팝업)\r\n");
      out.write("	<!-- 			<form action=\"/first/binsert\" method=\"post\" enctype=\"multipart/form-data\"> -->\r\n");
      out.write("					\r\n");
      out.write("					<div>애칭 &nbsp; <input type=\"text\" name=\"myplantName\"></div>\r\n");
      out.write("					<div>품종 &nbsp; <input type=\"text\" name=\"myplantVariety\"></div>\r\n");
      out.write("					<div>사진 &nbsp; <input type=\"file\" name=\"myplantImageURL\"></div>\r\n");
      out.write("					<div>메모 &nbsp; <input type=\"text\" name=\"myplantMemo\"></div>\r\n");
      out.write("					<div>키우기 시작한 날 &nbsp; <input type=\"date\" name=\"myplantStartDate\"></div>\r\n");
      out.write("					<div>함께한 날 &nbsp; </div>\r\n");
      out.write("					<div>성장환경 : \r\n");
      out.write("						<div class=\"position\"> 어떤 장소에서 키우나요 <br>\r\n");
      out.write("							<input type=\"radio\" name=\"posWindow\">창가 \r\n");
      out.write("							<input type=\"radio\" name=\"posVeranda\">베란다 \r\n");
      out.write("							<input type=\"radio\" name=\"posDesk\">책상\r\n");
      out.write("							<input type=\"radio\" name=\"posYard\">마당 \r\n");
      out.write("							<input type=\"radio\" name=\"posGarden\">텃밭 \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"environment\"> 어떤 환경에서 키우나요 <br>\r\n");
      out.write("							<input type=\"radio\" name=\"envSunny\">볕이 좋은\r\n");
      out.write("							<input type=\"radio\" name=\"envShady\">그늘진 \r\n");
      out.write("							<input type=\"radio\" name=\"envWindy\">바람 부는\r\n");
      out.write("							<input type=\"radio\" name=\"envDry\">건조한\r\n");
      out.write("							<input type=\"radio\" name=\"envHumid\">습한\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"with\"> 누구와 함께 키우나요 <br>\r\n");
      out.write("							<input type=\"radio\" name=\"withPet\">애완동물과함께\r\n");
      out.write("							<input type=\"radio\" name=\"withPlant\">식물들과함께\r\n");
      out.write("							<input type=\"radio\" name=\"withChild\">아이들과함께\r\n");
      out.write("							<input type=\"radio\" name=\"withFriend\">친구와함께\r\n");
      out.write("							<input type=\"radio\" name=\"withAlone\">혼자 \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"reset\" class=\"close-btn\" value=\"취소\">\r\n");
      out.write("						<input type=\"submit\" id=\"save\" class=\"save-close-btn\" value=\"저장\">\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					</div> <!-- myplantAdd -->\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("		");
 for (Myplant mp : list) { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div id=\"myplantListbody\">\r\n");
      out.write("			\r\n");
      out.write("				<div id=\"myplantbox\" class=\"myplantbox\"> \r\n");
      out.write("						<div class=\"nickname\">애칭 ");
      out.print( mp.getMyplantName() );
      out.write("</div>\r\n");
      out.write("						<div class=\"image\"><img src=\"#\"></div>\r\n");
      out.write("						<div class=\"information\">\r\n");
      out.write("							<div class=\"ID\">ID : ");
      out.print( mp.getMyplantId() );
      out.write("</div>\r\n");
      out.write("							<div class=\"variety\">품종 : ");
      out.print( mp.getMyplantVariety() );
      out.write("</div>\r\n");
      out.write("							<div class=\"Dday\">함께한 날 : ");
      out.print( mp.getMyplantStartDate() );
      out.write("</div>\r\n");
      out.write("							<div class=\"memo\">메모 : ");
      out.print( mp.getMyplantMemo() );
      out.write("</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div><!-- myplantbox -->\r\n");
      out.write("	\r\n");
      out.write("				<div id=\"myplantDetail\" class=\"myplantDetail\"> 디테일화면 (팝업)\r\n");
      out.write("	<!-- 			<form action=\"/first/binsert\" method=\"post\" enctype=\"multipart/form-data\"> -->\r\n");
      out.write("					\r\n");
      out.write("					<div>애칭: ");
      out.print( mp.getMyplantName() );
      out.write("</div>\r\n");
      out.write("					<div>품종: ");
      out.print( mp.getMyplantVariety() );
      out.write("</div>\r\n");
      out.write("					<div><img src=\"");
      out.print( mp.getMyplantImageURL() );
      out.write("\"></div>0\r\n");
      out.write("					<div>키우기 시작한 날: </div>\r\n");
      out.write("					<div>함께한 날: </div>\r\n");
      out.write("					<div>메모: ");
      out.print( mp.getMyplantMemo() );
      out.write("</div>\r\n");
      out.write("					<div>성장환경 : \r\n");
      out.write("						<div class=\"position\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">창가 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">베란다 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">책상\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">마당 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">텃밭 \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"environment\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">볕이 좋은\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">그늘진 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">바람 부는\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">건조한\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">습한\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"with\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">애완동물과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">식물들과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">아이들과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">친구와함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">혼자 \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button id=\"modify\" class=\"modify\" >수정</button>\r\n");
      out.write("						<button onclick=\"requestDelete(); return false;\">삭제</button>\r\n");
      out.write("						<button class=\"close-btn\">확인</button>	\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					</div> <!-- myplantDetail -->\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<form action=\"/malant/mpupdate\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<div id=\"myplantModify\" class=\"myplantModify\"> 디테일 편집화면 (팝업)\r\n");
      out.write("	<!-- 			<form action=\"/first/binsert\" method=\"post\" enctype=\"multipart/form-data\"> -->\r\n");
      out.write("					\r\n");
      out.write("					<div>애칭: ");
      out.print( mp.getMyplantName() );
      out.write("</div>\r\n");
      out.write("					<div>품종: ");
      out.print( mp.getMyplantVariety() );
      out.write("</div>\r\n");
      out.write("					<div><img src=\"");
      out.print( mp.getMyplantImageURL() );
      out.write("\"></div>0\r\n");
      out.write("					<div>키우기 시작한 날: </div>\r\n");
      out.write("					<div>함께한 날: </div>\r\n");
      out.write("					<div>메모: ");
      out.print( mp.getMyplantMemo() );
      out.write("</div>\r\n");
      out.write("					<div>성장환경 : \r\n");
      out.write("						<div class=\"position\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">창가 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">베란다 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">책상\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">마당 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">텃밭 \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"environment\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">볕이 좋은\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">그늘진 \r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">바람 부는\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">건조한\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">습한\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"with\">\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">애완동물과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">식물들과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">아이들과함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">친구와함께\r\n");
      out.write("							<input type=\"radio\" readonly checked=\"");
      out.print( mp.getPosWindow() );
      out.write("\">혼자 \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button class=\"close-btn\">취소</button>\r\n");
      out.write("						<button onclick=\"requestDelete(); return false;\">삭제</button>\r\n");
      out.write("						<button class=\"save-close-btn\">저장</button>	\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					</div> <!-- myplantModify -->\r\n");
      out.write("					</form>\r\n");
      out.write("						");
 } 
      out.write(" <!-- for문 -->\r\n");
      out.write("					<!-- <div id=\"ovelay\" ></div> -->\r\n");
      out.write("			</div> <!-- myplantListbody -->\r\n");
      out.write("			\r\n");
      out.write("		");
 }else if(list.size() == 0) { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div id=\"addYourPlant\" class=\"addYourPlant\"> 반려식물을 등록해주세요! </div>\r\n");
      out.write("			\r\n");
      out.write("			<form action=\"/malant/mpnew\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("			<div id=\"myplantAdd\" class=\"myplantAdd\"> 반려식물 등록화면 (팝업)\r\n");
      out.write("	<!-- 			<form action=\"/first/binsert\" method=\"post\" enctype=\"multipart/form-data\"> -->\r\n");
      out.write("					\r\n");
      out.write("					<div>애칭: </div>\r\n");
      out.write("					<div>품종: </div>\r\n");
      out.write("					<div><img src=\"#\"></div>0\r\n");
      out.write("					<div>키우기 시작한 날: </div>\r\n");
      out.write("					<div>함께한 날: </div>\r\n");
      out.write("					<div>메모: </div>\r\n");
      out.write("					<div>성장환경 : \r\n");
      out.write("						<div class=\"position\">\r\n");
      out.write("							<input type=\"radio\" readonly >창가 \r\n");
      out.write("							<input type=\"radio\" readonly >베란다 \r\n");
      out.write("							<input type=\"radio\" readonly >책상\r\n");
      out.write("							<input type=\"radio\" readonly >마당 \r\n");
      out.write("							<input type=\"radio\" readonly >텃밭 \r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"environment\">\r\n");
      out.write("							<input type=\"radio\" readonly >볕이 좋은\r\n");
      out.write("							<input type=\"radio\" readonly >그늘진 \r\n");
      out.write("							<input type=\"radio\" readonly >바람 부는\r\n");
      out.write("							<input type=\"radio\" readonly >건조한\r\n");
      out.write("							<input type=\"radio\" readonly >습한\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"with\">\r\n");
      out.write("							<input type=\"radio\" readonly >애완동물과함께\r\n");
      out.write("							<input type=\"radio\" readonly >식물들과함께\r\n");
      out.write("							<input type=\"radio\" readonly >아이들과함께\r\n");
      out.write("							<input type=\"radio\" readonly >친구와함께\r\n");
      out.write("							<input type=\"radio\" readonly >혼자 \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<button class=\"close-btn\">취소</button>\r\n");
      out.write("						<button class=\"save-close-btn\">저장</button>	\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					</div> <!-- myplantAdd -->\r\n");
      out.write("				</form>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div> <!-- content body  -->\r\n");
      out.write("	</div> <!-- main -->	\r\n");
      out.write("</div> <!-- container -->\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"/malant/resources/diary/js/myplant.js\"></script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
