/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-28 11:21:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enrollSeller_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Malant</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.input-container {\r\n");
      out.write("		width: 500px;\r\n");
      out.write("		height: 600px;\r\n");
      out.write("		border: 1px solid red;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.inputform {\r\n");
      out.write("		width: 450px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		margin: 5px auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.checkbox-container {\r\n");
      out.write("		width: 400px;\r\n");
      out.write("		height: 70px;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		border: 1px solid red;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.submit-btn_show {\r\n");
      out.write("		width: 450px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		border: 1px solid red;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.submit-btn_hide {\r\n");
      out.write("		width: 450px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/malant/resources/common/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"form-title\">판매회원 가입</div>\r\n");
      out.write("	<div class=\"input-container\">\r\n");
      out.write("		<form action=\"/malant/menroll\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"signtype\" value=\"seller\">\r\n");
      out.write("			<div class=\"input-id\">\r\n");
      out.write("				<input type=\"text\" class=\"inputform\" name=\"id\" size=\"20\" placeholder=\"아이디\"><br>\r\n");
      out.write("				<div class=\"input-guide-id\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-pwd\">\r\n");
      out.write("				<input type=\"password\" class=\"inputform\" name=\"pwd\" placeholder=\"비밀번호(영문+숫자+특수문자)\"><br>\r\n");
      out.write("				<div class=\"input-guide-pwd\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-pwd2\">\r\n");
      out.write("				<input type=\"password\" class=\"inputform\" name=\"pwd2\" placeholder=\"비밀번호 확인\"><br>\r\n");
      out.write("				<div class=\"input-guide-pwd2\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-name\">\r\n");
      out.write("				<input type=\"text\" class=\"inputform\" name=\"name\" size=\"20\" placeholder=\"이름\"><br>\r\n");
      out.write("				<div class=\"input-guide-name\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-email\">\r\n");
      out.write("				<input type=\"email\" class=\"inputform\" name=\"email\" placeholder=\"이메일\"><br>\r\n");
      out.write("				<div class=\"input-guide-email\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-phone\">\r\n");
      out.write("				<input type=\"tel\" class=\"inputform\" name=\"phone\" placeholder=\"핸드폰번호\">\r\n");
      out.write("				<div>인증요청</div><br>\r\n");
      out.write("				<div class=\"input-pwd2-guide\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div style=\"position: relative; left: 25px;\"><input type=\"checkbox\">약관 모두 동의 체크박스</div>\r\n");
      out.write("			<div class=\"checkbox-container\">\r\n");
      out.write("				<div><input type=\"checkbox\">판매 이용약관</div>\r\n");
      out.write("				<div><input type=\"checkbox\">전자금융거래이용약관</div>\r\n");
      out.write("				<div><input type=\"checkbox\">판매자 개인정보 수집 및 이용 동의</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"submit-btn_show\">\r\n");
      out.write("				동의하고 가입하기\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"submit\" class=\"submit-btn_hide\" value=\"동의하고 가입하기\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
