/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-01 01:56:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("	<!DOCTYPE html>\n");
      out.write("	<html>\n");
      out.write("\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"UTF-8\">\n");
      out.write("		<title>Malant</title>\n");
      out.write("		<script src=\"/malant/resources/common/js/jquery-3.7.0.min.js\"></script>\n");
      out.write("		<style>\n");
      out.write("			@import url(\"https://fonts.googleapis.com/css?family=Open+Sans:300,400|Lora\");\n");
      out.write("\n");
      out.write("			body {\n");
      out.write("				background: #CBC0D3;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			/* div box styling */\n");
      out.write("			.container {\n");
      out.write("				margin: auto;\n");
      out.write("				width: 650px;\n");
      out.write("				height: 550px;\n");
      out.write("				position: relative;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.welcome {\n");
      out.write("				background: #f6f6f6;\n");
      out.write("				width: 650px;\n");
      out.write("				height: 415px;\n");
      out.write("				position: absolute;\n");
      out.write("				top: 25%;\n");
      out.write("				border-radius: 5px;\n");
      out.write("				box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1);\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.pinkbox {\n");
      out.write("				position: absolute;\n");
      out.write("				top: -10%;\n");
      out.write("				left: 5%;\n");
      out.write("				background: #EAC7CC;\n");
      out.write("				width: 320px;\n");
      out.write("				height: 500px;\n");
      out.write("				border-radius: 5px;\n");
      out.write("				box-shadow: 2px 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("				transition: all 0.5s ease-in-out;\n");
      out.write("				z-index: 2;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.nodisplay {\n");
      out.write("				display: none;\n");
      out.write("				transition: all 0.5s ease;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.leftbox,\n");
      out.write("			.rightbox {\n");
      out.write("				position: absolute;\n");
      out.write("				width: 50%;\n");
      out.write("				transition: 1s all ease;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.leftbox {\n");
      out.write("				left: -2%;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.rightbox {\n");
      out.write("				right: -2%;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			/* font & button styling */\n");
      out.write("			h1 {\n");
      out.write("				font-family: \"Open Sans\", sans-serif;\n");
      out.write("				text-align: center;\n");
      out.write("				margin-top: 95px;\n");
      out.write("				text-transform: uppercase;\n");
      out.write("				color: #f6f6f6;\n");
      out.write("				font-size: 2em;\n");
      out.write("				letter-spacing: 8px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			h1#signup-box {\n");
      out.write("				font-family: \"Open Sans\", sans-serif;\n");
      out.write("				text-align: center;\n");
      out.write("				margin-top: 60px;\n");
      out.write("				text-transform: uppercase;\n");
      out.write("				color: #f6f6f6;\n");
      out.write("				font-size: 2em;\n");
      out.write("				letter-spacing: 8px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.title {\n");
      out.write("				font-family: \"Lora\", serif;\n");
      out.write("				color: #8E9AAF;\n");
      out.write("				font-size: 1.8em;\n");
      out.write("				line-height: 1.1em;\n");
      out.write("				letter-spacing: 3px;\n");
      out.write("				text-align: center;\n");
      out.write("				font-weight: 300;\n");
      out.write("				margin-top: 20%;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.desc {\n");
      out.write("				margin-top: -8px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.account {\n");
      out.write("				margin-top: 45%;\n");
      out.write("				font-size: 10px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			p {\n");
      out.write("				font-family: \"Open Sans\", sans-serif;\n");
      out.write("				font-size: 0.7em;\n");
      out.write("				letter-spacing: 2px;\n");
      out.write("				color: #8E9AAF;\n");
      out.write("				text-align: center;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			span {\n");
      out.write("				color: #EAC7CC;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.flower {\n");
      out.write("				position: absolute;\n");
      out.write("				width: 120px;\n");
      out.write("				height: 120px;\n");
      out.write("				top: 46%;\n");
      out.write("				left: 29%;\n");
      out.write("				opacity: 0.7;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.smaller {\n");
      out.write("				width: 90px;\n");
      out.write("				height: 100px;\n");
      out.write("				top: 48%;\n");
      out.write("				left: 38%;\n");
      out.write("				opacity: 0.9;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			button {\n");
      out.write("				padding: 12px;\n");
      out.write("				font-family: \"Open Sans\", sans-serif;\n");
      out.write("				text-transform: uppercase;\n");
      out.write("				letter-spacing: 3px;\n");
      out.write("				font-size: 11px;\n");
      out.write("				border-radius: 10px;\n");
      out.write("				margin: auto;\n");
      out.write("				outline: none;\n");
      out.write("				display: block;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			button:hover {\n");
      out.write("				background: #EAC7CC;\n");
      out.write("				color: #f6f6f6;\n");
      out.write("				transition: background-color 1s ease-out;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.button {\n");
      out.write("				margin-top: 3%;\n");
      out.write("				background: #f6f6f6;\n");
      out.write("				color: #ce7d88;\n");
      out.write("				border: solid 1px #EAC7CC;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			/* form styling */\n");
      out.write("			form {\n");
      out.write("				display: flex;\n");
      out.write("				align-items: center;\n");
      out.write("				flex-direction: column;\n");
      out.write("				padding-top: 7px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.more-padding {\n");
      out.write("				padding-top: 35px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.more-padding input {\n");
      out.write("				padding: 12px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.more-padding .submit {\n");
      out.write("				margin-top: 45px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.submit {\n");
      out.write("				margin-top: 25px;\n");
      out.write("				padding: 12px;\n");
      out.write("				border-color: #ce7d88;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.submit:hover {\n");
      out.write("				background: #CBC0D3;\n");
      out.write("				border-color: #bfb1c9;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			input {\n");
      out.write("				background: #EAC7CC;\n");
      out.write("				width: 65%;\n");
      out.write("				color: #ce7d88;\n");
      out.write("				border: none;\n");
      out.write("				border-bottom: 1px solid rgba(246, 246, 246, 0.5);\n");
      out.write("				padding: 9px;\n");
      out.write("				margin: 7px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			input::placeholder {\n");
      out.write("				color: #f6f6f6;\n");
      out.write("				letter-spacing: 2px;\n");
      out.write("				font-size: 1.3em;\n");
      out.write("				font-weight: 100;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			input:focus {\n");
      out.write("				color: #ce7d88;\n");
      out.write("				outline: none;\n");
      out.write("				border-bottom: 1.2px solid rgba(206, 125, 136, 0.7);\n");
      out.write("				font-size: 1em;\n");
      out.write("				transition: 0.8s all ease;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			input:focus::placeholder {\n");
      out.write("				opacity: 0;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			label {\n");
      out.write("				font-family: \"Open Sans\", sans-serif;\n");
      out.write("				color: #ce7d88;\n");
      out.write("				font-size: 0.8em;\n");
      out.write("				letter-spacing: 1px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.checkbox {\n");
      out.write("				display: inline;\n");
      out.write("				white-space: nowrap;\n");
      out.write("				position: relative;\n");
      out.write("				left: -62px;\n");
      out.write("				top: 5px;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			input[type=checkbox] {\n");
      out.write("				width: 7px;\n");
      out.write("				background: #ce7d88;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.checkbox input[type=checkbox]:checked+label {\n");
      out.write("				color: #ce7d88;\n");
      out.write("				transition: 0.5s all ease;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			/*# sourceMappingURL=loginPage.css.map */\n");
      out.write("		</style>\n");
      out.write("		<script>\n");
      out.write("			/* 유효성 검사 */\n");
      out.write("			function validate() {\n");
      out.write("				var id = $('#userid');\n");
      out.write("				var pwd = $('#pwd');\n");
      out.write("				var pwd2 = $('#pwd2');\n");
      out.write("				var email = $('#email');\n");
      out.write("				var nickname = $('#nickname');\n");
      out.write("				\n");
      out.write("				var id_rgx = /^[A-Za-z]{1}[A-Za-z0-9]{5,11}$/;\n");
      out.write("				var pwd_rgx = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$/;\n");
      out.write("\n");
      out.write("				/* 아이디 유효성 검사 */\n");
      out.write("				var id_len = id.val().length;\n");
      out.write("				if(id_len < 6 || id_len > 12) {\n");
      out.write("					alert(\"아이디는 6글자 이상이여야합니다.\");\n");
      out.write("					id.select();\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("				if(!id_rgx.test(id.val())) {\n");
      out.write("					alert(\"아이디는 영문과 숫자만을 포함해야합니다.\");\n");
      out.write("					id.select();\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				/* 닉네임 유효성 검사 */\n");
      out.write("				var name_len = nickname.val().length;\n");
      out.write("				if(name_len < 2 || name_len > 8) {\n");
      out.write("					alert(\"닉네임은 2글자 이상이여야 합니다.\");\n");
      out.write("					nickname.select();\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				/* 비밀번호 유효성 검사 */\n");
      out.write("				var pwd_len = pwd.val().length;\n");
      out.write("\n");
      out.write("				console.log(\"pwd : \" + pwd.val() + \", pwd2 : \" + pwd2.val());\n");
      out.write("				console.log(\"pwd_len : \" + pwd.val().length + \", pwd2_len : \" + pwd2.val().length);\n");
      out.write("				if(pwd.val() != pwd2.val()) {\n");
      out.write("					alert(\"비밀번호가 일치하지 않습니다.\");\n");
      out.write("					pwd2.select();\n");
      out.write("					return false;\n");
      out.write("				} else if(!pwd_rgx.test(pwd.val())) {\n");
      out.write("					alert(\"비밀번호는 영문/숫자/특수문자를 모두 포함하고, 8글자 이상이여야 합니다.\");\n");
      out.write("					pwd.select();\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				if(!dupCheck()) {\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				return true;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function dupCheck() {\n");
      out.write("				$.ajax({\n");
      out.write("					url: '/malant/checkdup',\n");
      out.write("					type: 'post',\n");
      out.write("					data: {\n");
      out.write("						userid: $('#userid').val(),\n");
      out.write("						email: $('#email').val()\n");
      out.write("					},\n");
      out.write("					dataType: \"json\",\n");
      out.write("					success: function(data) {\n");
      out.write("						console.log(\"date : \" + data + \", datatype : \" + typeof(data));\n");
      out.write("						if(data.dupid != \"ok\") {\n");
      out.write("							alert(\"이미 사용중인 아이디입니다.\");\n");
      out.write("							return false;\n");
      out.write("						} else if(data.dupemail != \"ok\") {\n");
      out.write("							alert(\"이미 사용중인 이메일입니다.\");\n");
      out.write("							return false;\n");
      out.write("						}\n");
      out.write("					},\n");
      out.write("					error: function(jqXHR, textStatus, errorThrown){\n");
      out.write("						console.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" + errorThrown);\n");
      out.write("					}\n");
      out.write("				});\n");
      out.write("\n");
      out.write("				return true;\n");
      out.write("			}\n");
      out.write("		</script>\n");
      out.write("	</head>\n");
      out.write("\n");
      out.write("	<body>\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"welcome\">\n");
      out.write("				<div class=\"pinkbox\">\n");
      out.write("					<div class=\"signup nodisplay\">\n");
      out.write("						<h1 id=\"signup-box\">회원가입</h1>\n");
      out.write("						<form action=\"/malant/menroll\" method=\"post\" autocomplete=\"off\" onsubmit=\"return validate();\">\n");
      out.write("							<input type=\"hidden\" name=\"signtype\" value=\"common\">\n");
      out.write("							<input type=\"text\" id=\"userid\" name=\"userid\" maxlength=\"12\" placeholder=\"아이디\" required>\n");
      out.write("							<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"이메일\" required>\n");
      out.write("							<input type=\"text\" id=\"nickname\" name=\"nickname\" maxlength=\"8\" placeholder=\"닉네임\" required>\n");
      out.write("							<input type=\"password\" id=\"pwd\" name=\"userpwd\" maxlength=\"25\" placeholder=\"비밀번호\" required>\n");
      out.write("							<input type=\"password\" id=\"pwd2\" maxlength=\"25\" placeholder=\"비밀번호 확인\" required>\n");
      out.write("							<button class=\"button submit\">가입하기</button>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"signin\">\n");
      out.write("						<h1>Malant</h1>\n");
      out.write("						<form action=\"/malant/login\" method=\"post\" class=\"more-padding\" autocomplete=\"off\">\n");
      out.write("							\n");
      out.write("							<input type=\"text\" name=\"userid\" placeholder=\"아이디\" required>\n");
      out.write("							<input type=\"password\" name=\"userpwd\" placeholder=\"패스워드\" required>\n");
      out.write("							<button class=\"button submit\">로그인</button>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"leftbox\">\n");
      out.write("					<h2 class=\"title\"><span>BLOOM</span>&<br>BOUQUET</h2>\n");
      out.write("					<p class=\"desc\">pick your perfect <span>bouquet</span></p>\n");
      out.write("					<img class=\"flower smaller\" src=\"https://image.ibb.co/d5X6pn/1357d638624297b.jpg\"\n");
      out.write("						alt=\"1357d638624297b\" border=\"0\">\n");
      out.write("					<p class=\"account\">have an account?</p>\n");
      out.write("					<button class=\"button\" id=\"signin\">로그인</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"rightbox\">\n");
      out.write("					<h2 class=\"title\"><span>BLOOM</span>&<br>BOUQUET</h2>\n");
      out.write("					<p class=\"desc\"> pick your perfect <span>bouquet</span></p>\n");
      out.write("					<img class=\"flower\" src=\"https://preview.ibb.co/jvu2Un/0057c1c1bab51a0.jpg\" />\n");
      out.write("					<p class=\"account\">don't have an account?</p>\n");
      out.write("					<button class=\"button\" id=\"signup\">회원가입</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<script>\n");
      out.write("			$('#signup').click(function () {\n");
      out.write("				$('.pinkbox').css('transform', 'translateX(80%)');\n");
      out.write("				$('.signin').addClass('nodisplay');\n");
      out.write("				$('.signup').removeClass('nodisplay');\n");
      out.write("			});\n");
      out.write("\n");
      out.write("			$('#signin').click(function () {\n");
      out.write("				$('.pinkbox').css('transform', 'translateX(0%)');\n");
      out.write("				$('.signup').addClass('nodisplay');\n");
      out.write("				$('.signin').removeClass('nodisplay');\n");
      out.write("			});\n");
      out.write("		</script>\n");
      out.write("	</body>\n");
      out.write("\n");
      out.write("	</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
